# Generated by Django 3.1.12 on 2025-01-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanda_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='approved',
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('disapproved', 'Disapproved')], default='pending', max_length=11),
        ),
    ]
